import { getDb, genId, genToken } from '@/lib/db';
import * as fs from '@/lib/file-store';

export type Repo = { id: string; name: string; description: string; visibility: 'public' | 'private'; default_branch: string; created_at: string; updated_at: string; };
export type Branch = { id: string; repo_id: string; name: string; parent_branch: string | null; created_at: string; };
export type Snapshot = { id: string; repo_id: string; branch_id: string; message: string; author: string; file_index: string; created_at: string; };
export type TokenRecord = { id: string; token: string; name: string; enabled: boolean; expires_at: string | null; created_at: string; };
export type RepoLog = { id: number; repo_id: string | null; action: string; detail: string; created_at: string; };
export type DeploySource = { project_id: string; repo_id: string; branch_id: string; last_synced_at: string | null; created_at: string; };
export type FileNode = { name: string; path: string; type: 'file' | 'dir'; children?: FileNode[]; };

async function logAction(repoId: string, action: string, detail: string): Promise<void> { const db = await getDb(); await db.query('INSERT INTO repo_logs (repo_id, action, detail) VALUES ($1, $2, $3)', [repoId, action, detail]); }

export async function createRepo(name: string, description = '', visibility: 'public' | 'private' = 'private'): Promise<Repo> { const db = await getDb(); const id = genId('repo'); await db.query('INSERT INTO repos (id, name, description, visibility, default_branch) VALUES ($1, $2, $3, $4, $5)', [id, name, description, visibility, 'main']); const branchId = genId('br'); await db.query('INSERT INTO branches (id, repo_id, name, parent_branch) VALUES ($1, $2, $3, $4)', [branchId, id, 'main', null]); await fs.writeFile(id, branchId, 'README.md', `# ${name}\n\nWelcome to ${name}.\n`); await logAction(id, 'repo.created', `Repository "${name}" created`); return (await getRepo(id))!; }
export async function getRepo(id: string): Promise<Repo | null> { const db = await getDb(); const res = await db.query<Repo>('SELECT * FROM repos WHERE id = $1', [id]); return res.rows[0] || null; }
export async function listRepos(): Promise<Repo[]> { const db = await getDb(); const res = await db.query<Repo>('SELECT * FROM repos ORDER BY updated_at DESC'); return res.rows; }
export async function renameRepo(id: string, newName: string): Promise<void> { const db = await getDb(); await db.query('UPDATE repos SET name = $1, updated_at = now() WHERE id = $2', [newName, id]); await logAction(id, 'repo.renamed', `Renamed to "${newName}"`); }
export async function deleteRepo(id: string): Promise<void> { const db = await getDb(); const repo = await getRepo(id); await db.query('DELETE FROM repos WHERE id = $1', [id]); await fs.deleteRepoFiles(id); if (repo) await logAction(id, 'repo.deleted', `Repository "${repo.name}" deleted`); }
export async function toggleVisibility(id: string): Promise<void> { const db = await getDb(); const repo = await getRepo(id); if (!repo) return; const newVis = repo.visibility === 'public' ? 'private' : 'public'; await db.query('UPDATE repos SET visibility = $1, updated_at = now() WHERE id = $2', [newVis, id]); await logAction(id, 'repo.visibility', `Visibility changed to ${newVis}`); }

export async function listBranches(repoId: string): Promise<Branch[]> { const db = await getDb(); const res = await db.query<Branch>('SELECT * FROM branches WHERE repo_id = $1 ORDER BY created_at', [repoId]); return res.rows; }
export async function getBranchByName(repoId: string, name: string): Promise<Branch | null> { const db = await getDb(); const res = await db.query<Branch>('SELECT * FROM branches WHERE repo_id = $1 AND name = $2', [repoId, name]); return res.rows[0] || null; }
export async function getBranchById(repoId: string, branchId: string): Promise<Branch | null> { const db = await getDb(); const res = await db.query<Branch>('SELECT * FROM branches WHERE repo_id = $1 AND id = $2', [repoId, branchId]); return res.rows[0] || null; }
export async function createBranch(repoId: string, name: string, parentBranchId: string): Promise<Branch> { const db = await getDb(); const parent = await getBranchById(repoId, parentBranchId); const id = genId('br'); await db.query('INSERT INTO branches (id, repo_id, name, parent_branch) VALUES ($1, $2, $3, $4)', [id, repoId, name, parent?.name || null]); if (parent) await fs.copyBranchFiles(repoId, parent.id, id); await logAction(repoId, 'branch.created', `Branch "${name}" created from "${parent?.name || 'root'}"`); return (await getBranchById(repoId, id))!; }
export async function deleteBranch(repoId: string, branchId: string): Promise<void> { const db = await getDb(); const branch = await getBranchById(repoId, branchId); if (!branch) return; const repo = await getRepo(repoId); if (repo && repo.default_branch === branch.name) return; await db.query('DELETE FROM branches WHERE id = $1', [branchId]); await fs.deleteBranchFiles(repoId, branchId); await logAction(repoId, 'branch.deleted', `Branch "${branch.name}" deleted`); }
export async function mergeBranch(repoId: string, sourceBranchId: string, targetBranchId: string): Promise<{ merged: number; conflicts: string[] }> { const result = await fs.mergeBranchFiles(repoId, sourceBranchId, targetBranchId); const source = await getBranchById(repoId, sourceBranchId); const target = await getBranchById(repoId, targetBranchId); await createSnapshot(repoId, targetBranchId, `Merge ${source?.name || 'unknown'} into ${target?.name || 'unknown'}`); await logAction(repoId, 'branch.merged', `Merged "${source?.name}" into "${target?.name}" (${result.merged} files, ${result.conflicts.length} conflicts)`); return result; }

export async function listBranchFiles(repoId: string, branchId: string): Promise<string[]> { return fs.listFiles(repoId, branchId); }
export async function readFile(repoId: string, branchId: string, path: string): Promise<string | null> { return fs.readFile(repoId, branchId, path); }
export async function saveFile(repoId: string, branchId: string, path: string, content: string, message?: string): Promise<Snapshot> { await fs.writeFile(repoId, branchId, path, content); const db = await getDb(); await db.query('UPDATE repos SET updated_at = now() WHERE id = $1', [repoId]); const snap = await createSnapshot(repoId, branchId, message || `Updated ${path}`); await logAction(repoId, 'file.saved', `Saved ${path}`); return snap; }
export async function createFile(repoId: string, branchId: string, path: string, content = '', message?: string): Promise<Snapshot> { await fs.writeFile(repoId, branchId, path, content); const db = await getDb(); await db.query('UPDATE repos SET updated_at = now() WHERE id = $1', [repoId]); const snap = await createSnapshot(repoId, branchId, message || `Created ${path}`); await logAction(repoId, 'file.created', `Created ${path}`); return snap; }
export async function deleteFiles(repoId: string, branchId: string, paths: string[], message?: string): Promise<Snapshot> { await Promise.all(paths.map((p) => fs.deleteFile(repoId, branchId, p))); const db = await getDb(); await db.query('UPDATE repos SET updated_at = now() WHERE id = $1', [repoId]); const snap = await createSnapshot(repoId, branchId, message || `Deleted ${paths.length} file(s)`); await logAction(repoId, 'file.deleted', `Deleted: ${paths.join(', ')}`); return snap; }
export async function uploadFile(repoId: string, branchId: string, path: string, content: string, message?: string): Promise<Snapshot> { await fs.writeFile(repoId, branchId, path, content); const db = await getDb(); await db.query('UPDATE repos SET updated_at = now() WHERE id = $1', [repoId]); const snap = await createSnapshot(repoId, branchId, message || `Uploaded ${path}`); await logAction(repoId, 'file.uploaded', `Uploaded ${path}`); return snap; }

export async function createSnapshot(repoId: string, branchId: string, message: string): Promise<Snapshot> { const db = await getDb(); const id = genId('snap'); const fileMap = await fs.createSnapshotFiles(repoId, branchId, id); const fileIndex = JSON.stringify(Object.keys(fileMap)); await db.query('INSERT INTO snapshots (id, repo_id, branch_id, message, author, file_index) VALUES ($1, $2, $3, $4, $5, $6)', [id, repoId, branchId, message, 'user', fileIndex]); return (await getSnapshot(id))!; }
export async function getSnapshot(id: string): Promise<Snapshot | null> { const db = await getDb(); const res = await db.query<Snapshot>('SELECT * FROM snapshots WHERE id = $1', [id]); return res.rows[0] || null; }
export async function listSnapshots(repoId: string, branchId: string): Promise<Snapshot[]> { const db = await getDb(); const res = await db.query<Snapshot>('SELECT * FROM snapshots WHERE repo_id = $1 AND branch_id = $2 ORDER BY created_at DESC', [repoId, branchId]); return res.rows; }
export async function rollbackToSnapshot(repoId: string, branchId: string, snapshotId: string): Promise<void> { await fs.restoreSnapshotFiles(repoId, branchId, snapshotId); const snap = await getSnapshot(snapshotId); const db = await getDb(); await db.query('UPDATE repos SET updated_at = now() WHERE id = $1', [repoId]); await createSnapshot(repoId, branchId, `Rollback to: ${snap?.message || 'previous version'}`); await logAction(repoId, 'snapshot.rollback', `Rolled back to snapshot: ${snap?.message || snapshotId}`); }

export async function createToken(name = 'default', expiresAt: string | null = null): Promise<TokenRecord> { const db = await getDb(); const id = genId('tok'); const token = genToken(); await db.query('INSERT INTO tokens (id, token, name, enabled, expires_at) VALUES ($1, $2, $3, $4, $5)', [id, token, name, true, expiresAt]); return (await getTokenById(id))!; }
export async function getTokenById(id: string): Promise<TokenRecord | null> { const db = await getDb(); const res = await db.query<TokenRecord>('SELECT * FROM tokens WHERE id = $1', [id]); return res.rows[0] || null; }
export async function listTokens(): Promise<TokenRecord[]> { const db = await getDb(); const res = await db.query<TokenRecord>('SELECT * FROM tokens ORDER BY created_at DESC'); return res.rows; }
export async function deleteToken(id: string): Promise<void> { const db = await getDb(); await db.query('DELETE FROM tokens WHERE id = $1', [id]); }
export async function toggleToken(id: string): Promise<void> { const db = await getDb(); const tok = await getTokenById(id); if (!tok) return; await db.query('UPDATE tokens SET enabled = $1 WHERE id = $2', [!tok.enabled, id]); }
export async function validateToken(token: string): Promise<{ valid: boolean; reason?: string }> { const db = await getDb(); const res = await db.query<TokenRecord>('SELECT * FROM tokens WHERE token = $1', [token]); const tok = res.rows[0]; if (!tok) return { valid: false, reason: 'Token not found' }; if (!tok.enabled) return { valid: false, reason: 'Token is disabled' }; if (tok.expires_at && new Date(tok.expires_at) < new Date()) return { valid: false, reason: 'Token has expired' }; return { valid: true }; }
export async function getValidToken(): Promise<TokenRecord | null> { const tokens = await listTokens(); for (const tok of tokens) { if (tok.enabled && (!tok.expires_at || new Date(tok.expires_at) > new Date())) return tok; } return null; }

export async function setDeploySource(projectId: string, repoId: string, branchId: string): Promise<void> { const db = await getDb(); await db.query(`INSERT INTO deploy_sources (project_id, repo_id, branch_id) VALUES ($1, $2, $3) ON CONFLICT (project_id) DO UPDATE SET repo_id = $2, branch_id = $3`, [projectId, repoId, branchId]); await logAction(repoId, 'deploy.source.set', `Deploy source set for project ${projectId}`); }
export async function getDeploySource(projectId: string): Promise<DeploySource | null> { const db = await getDb(); const res = await db.query<DeploySource>('SELECT * FROM deploy_sources WHERE project_id = $1', [projectId]); return res.rows[0] || null; }
export async function removeDeploySource(projectId: string): Promise<void> { const db = await getDb(); await db.query('DELETE FROM deploy_sources WHERE project_id = $1', [projectId]); }
export async function syncDeployFiles(projectId: string): Promise<{ fileCount: number }> { const source = await getDeploySource(projectId); if (!source) throw new Error('No deploy source configured'); const files = await fs.getAllFilesForDeploy(source.repo_id, source.branch_id); const db = await getDb(); await db.query('UPDATE deploy_sources SET last_synced_at = now() WHERE project_id = $1', [projectId]); await logAction(source.repo_id, 'deploy.synced', `Synced ${Object.keys(files).length} files to project ${projectId}`); return { fileCount: Object.keys(files).length }; }

export async function listRepoLogs(repoId: string, limit = 50): Promise<RepoLog[]> { const db = await getDb(); const res = await db.query<RepoLog>('SELECT * FROM repo_logs WHERE repo_id = $1 ORDER BY created_at DESC LIMIT $2', [repoId, limit]); return res.rows; }

export function buildFileTree(paths: string[]): FileNode[] { const root: FileNode[] = []; const dirMap = new Map<string, FileNode>(); for (const fullPath of paths.sort()) { const parts = fullPath.split('/'); const fileName = parts[parts.length - 1]; const dirPath = parts.slice(0, -1).join('/'); let currentChildren = root; let currentPath = ''; for (let i = 0; i < parts.length - 1; i++) { const part = parts[i]; currentPath = currentPath ? `${currentPath}/${part}` : part; let dirNode = dirMap.get(currentPath); if (!dirNode) { dirNode = { name: part, path: currentPath, type: 'dir', children: [] }; dirMap.set(currentPath, dirNode); currentChildren.push(dirNode); } currentChildren = dirNode.children!; } currentChildren.push({ name: fileName, path: fullPath, type: 'file' }); } return root; }
